name: alpaca-parser-generator
version: '0.3.0.3'
author: Nikolay Yakimov
maintainer: root@livid.pp.ru
license: MIT
extra-source-files:
- CHANGELOG.md
executables:
  alpaca:
    build-tools:
    - alex
    - happy
    source-dirs:
      - .
      - lib
    main: Main.hs
    default-extensions: [DataKinds, KindSignatures]
    dependencies:
    - base >=4.12 && <5
    - text >=1.2.3 && <1.3
    - bytestring >=0.10.12.0 && <0.11
    - containers >=0.6.0 && <0.7
    - mtl >=2.2.2 && <2.3
    - array >=0.5.3 && <0.6 # Needed by alex code
    - table-layout >=0.8.0 && <0.10
    - string-interpolate >=0.2.0 && <0.4
    - template-haskell >=2.14.0 && <2.17 # For QuasiQuoter
    - directory >=1.3.3 && <1.4
    - filepath >=1.4.2 && <1.5
    - optparse-applicative >=0.15.1 && <0.17
